version: "3.9"

networks:
  quarkus:
    driver: bridge

services:
  microservice.a:
    image: magnaldomelo/quarkus-desafio:1.0.0-SNAPSHOT
    build:
      context: ./microservice.a
      dockerfile: Dockerfile
    ports:
      - "8181:8181"
    networks:
      - quarkus
  microservice.b:
    image: magnaldomelo/coopersystem.challenge:1.0.0-SNAPSHOT
    build:
      context: ./microservice.b
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - quarkus
    depends_on:
        - microservice.a
